/**
 * Purge demo / mock data so customer dashboards only ever show real applications.
 *
 * Deletes:
 *   - applications generated by mock runs (mock job urls, or "(demo)" reasons)
 *   - jobs with source = "mock"
 *   - reports (daily summaries are aggregates of runs; mock runs polluted them,
 *     and they regenerate on the next real run)
 *
 * Leaves users, profiles, credentials, and integrations untouched.
 *
 * Run locally:   node scripts/purge-demo.mjs
 * Run in prod:   docker compose exec web node scripts/purge-demo.mjs
 */
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("Purging demo/mock data…");

  // Mock applications: url points at a mock listing, or the reason carries the
  // "(demo)" marker the worker writes in mock mode.
  const apps = await prisma.application.deleteMany({
    where: {
      OR: [
        { url: { contains: "/mock-" } },
        { url: { contains: "detail/mock" } },
        { reason: { contains: "(demo)" } },
        { reason: { contains: "auto-applied (demo)" } },
      ],
    },
  });
  console.log(`  applications removed: ${apps.count}`);

  // Mock job rows.
  const jobs = await prisma.job.deleteMany({ where: { source: "mock" } });
  console.log(`  mock jobs removed:    ${jobs.count}`);

  // Daily reports — clear all; they re-accrue from real runs.
  const reports = await prisma.report.deleteMany();
  console.log(`  reports cleared:      ${reports.count}`);

  console.log("Done. Dashboards now reflect real applications only.");
}

main()
  .catch((e) => {
    console.error("purge failed:", e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
