/**
 * Purge demo / mock data so customer dashboards only ever show real applications.
 *
 * Deletes:
 *   - applications generated by mock runs (mock job urls, or "(demo)" reasons)
 *   - jobs with source = "mock"
 *   - OPTIONALLY, with --purge-reports: ALL daily reports for ALL users, mock
 *     and real alike (the Report model has no field distinguishing the two —
 *     it's a per-day aggregate, not a per-application row, so there's no way
 *     to scope this delete to "only the mock-tainted ones"). This used to run
 *     unconditionally, silently wiping every real user's report history too
 *     on a routine "clear the demo data" run — the exact kind of unguarded
 *     full-table wipe reset-db.mjs/purge-users.mjs were hardened against.
 *
 * Leaves users, profiles, credentials, and integrations untouched.
 *
 * Run locally:   node scripts/purge-demo.mjs
 * Run in prod:   docker compose exec web node scripts/purge-demo.mjs
 * Also wipe all daily reports (real + mock — see above): add --purge-reports
 */
import { PrismaClient } from "@prisma/client";

const purgeReports = process.argv.slice(2).includes("--purge-reports");

const prisma = new PrismaClient();

async function main() {
  console.log("Purging demo/mock data…");

  // Mock applications: url points at a mock listing, or the reason carries the
  // "(demo)" marker the worker writes in mock mode.
  const apps = await prisma.application.deleteMany({
    where: {
      OR: [
        { url: { contains: "/mock-" } },
        { url: { contains: "detail/mock" } },
        { reason: { contains: "(demo)" } },
        { reason: { contains: "auto-applied (demo)" } },
      ],
    },
  });
  console.log(`  applications removed: ${apps.count}`);

  // Mock job rows.
  const jobs = await prisma.job.deleteMany({ where: { source: "mock" } });
  console.log(`  mock jobs removed:    ${jobs.count}`);

  // Daily reports — clears EVERY user's report history, real included, since
  // there's no mock/real distinction on this model. Opt-in only.
  if (purgeReports) {
    const reports = await prisma.report.deleteMany();
    console.log(`  reports cleared:      ${reports.count} (--purge-reports was set)`);
  } else {
    console.log("  reports left alone (pass --purge-reports to also clear ALL users' report history)");
  }

  console.log("Done. Dashboards now reflect real applications only.");
}

main()
  .catch((e) => {
    console.error("purge failed:", e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
